spring.application.name=datronix
spring.datasource.url=jdbc:postgresql://100.83.236.14:5433/datronix
spring.datasource.username=postgres
spring.datasource.password=12131422
spring.datasource.driver-class-name=org.postgresql.Driver
# server.port=8089

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0
server.port=8080
